Repository WhileNotSuccess/project_Korean-Education-Center-Frontend_NextJS-deployment-repo, pull requests merged in 2025-02, with the labels that each got.

#11 어드민 페이지 제작
  web/src/app/(Layout)/admin/[category]/page.tsx
  web/src/app/(Layout)/admin/layout.tsx
  web/src/app/(Layout)/components/ApplicationComponent.tsx
  web/src/app/(Layout)/components/ApplicationFormItem.tsx
  web/src/app/(Layout)/components/CounselingItem.tsx
  web/src/app/common/types.tsx
Labels: ⭐ Feature

#14 상담 신청의 수정, 삭제 기능 추가
  web/src/app/(Layout)/admin/layout.tsx
  web/src/app/(Layout)/components/ApplicationComponent.tsx
  web/src/app/(Layout)/components/ApplicationFormItem.tsx
  web/src/app/(Layout)/components/BoardPageCompo.tsx
  web/src/app/(Layout)/components/CounselingItem.tsx
  web/src/app/(Layout)/components/CounselingItemDeleteModal.tsx
  web/src/app/(Layout)/components/CounselingItemUpdateModal.tsx
  web/src/app/(Layout)/components/EditorComponent.tsx
  web/src/app/common/formatDate.ts
  web/src/app/common/formatDateWithTime.ts
  web/src/app/common/types.tsx
Labels: 🛠️ Refactor, ⭐ Feature

#15 글 작성 페이지 완성, 세부사항이 있는 안내페이지 제작
  node_modules/.package-lock.json
  package-lock.json
  package.json
  web/package-lock.json
  web/package.json
  web/src/app/(Layout)/(introduce)/staff-intro/staffIntro.tsx
  web/src/app/(Layout)/components/BoardPageCompo.tsx
  web/src/app/(Layout)/components/EditorComponent.tsx
  web/src/app/(Layout)/components/HtmlDocs.tsx
  web/src/app/(Layout)/components/SchoolMap.tsx
  web/src/app/(Layout)/components/SelectPageCompo.tsx
  web/src/app/(Layout)/cookie-test/page.tsx
  web/src/app/(Layout)/home/page.tsx
  web/src/app/(Layout)/layout.tsx
  web/src/app/(Layout)/post-test/[category]/page.tsx
  web/src/app/(Layout)/post-test/page.tsx
  web/src/app/(Layout)/post-update-test/[id]/page.tsx
  web/src/app/(Layout)/post-update-test/page.tsx
  web/src/app/(Layout)/select/[category]/page.tsx
  web/src/app/common/Cookie.tsx
  web/src/app/menu.tsx
  web/tsconfig.json
Labels: ⭐ Feature

#20 관리자페이지 나머지 부분 구현
  web/src/app/(Layout)/admin/[category]/page.tsx
  web/src/app/(Layout)/components/AdminComponent.tsx
  web/src/app/(Layout)/components/BannerItem.tsx
  web/src/app/(Layout)/components/CounselingItem.tsx
  web/src/app/(Layout)/components/DeleteModal.tsx
  web/src/app/common/types.tsx
  web/src/app/menu.tsx
Labels: ⭐ Feature

#27 ✨ feat : 로그인 기능 추가, 상담 신청 페이지 제작
  node_modules/.package-lock.json
  package-lock.json
  web/package-lock.json
  web/package.json
  web/public/images/background.jpg
  web/public/images/logintab.png
  web/src/app/(Layout)/components/FormCompo.tsx
  web/src/app/(Layout)/components/HtmlDocs.tsx
  web/src/app/(Layout)/components/LoginCompo.tsx
  web/src/app/(Layout)/components/SelectPageCompo.tsx
  web/src/app/(Layout)/form/[category]/page.tsx
  web/src/app/(Layout)/home/page.tsx
  web/src/app/(Layout)/layout.tsx
  web/src/app/(Layout)/select/[category]/page.tsx
  web/src/app/(NoLayout)/components/CheckNewUser.tsx
  web/src/app/(NoLayout)/components/LoginForm.tsx
  web/src/app/(NoLayout)/components/RegisterCompo.tsx
  web/src/app/(NoLayout)/layout.tsx
  web/src/app/(NoLayout)/login/layout.tsx
  web/src/app/(NoLayout)/login/page.tsx
  web/src/app/(NoLayout)/register/page.tsx
  web/src/app/hook/auth.ts
  web/src/app/menu.tsx
Labels: ⭐ Feature

#31 로그인 가능하게 수정
  web/package-lock.json
  web/src/app/(Layout)/components/LoginCompo.tsx
  web/src/app/(Layout)/dashboard/page.tsx
  web/src/app/(Layout)/layout.tsx
  web/src/app/(Layout)/need-link/page.tsx
  web/src/app/(NoLayout)/components/CheckNewUser.tsx
  web/src/app/(NoLayout)/components/LoginForm.tsx
  web/src/app/(NoLayout)/components/RegisterCompo.tsx
  web/src/app/common/Cookie.tsx
  web/src/app/common/types.tsx
  web/src/app/hook/auth.ts
  web/src/app/lib/customFetch.ts
Labels: 🐛 BugFix, 🛠️ Refactor, ⭐ Feature

#35 어드민 페이지 완성
  web/src/app/(Layout)/admin/page.tsx
  web/src/app/(Layout)/components/AdminComponent.tsx
  web/src/app/(Layout)/components/ApplicationFormItem.tsx
  web/src/app/(Layout)/components/BannerPostModal.tsx
  web/src/app/common/types.tsx
  web/src/app/lib/customFormFetch.ts
Labels: ⭐ Feature

#36 Home 페이지 알림 로직 추가, 페이지 디자인 전체 수정
  web/public/images/faq.png
  web/public/images/home.png
  web/public/images/light.png
  web/public/images/review.png
  web/public/images/문서1.png
  web/public/images/학사모1.png
  web/src/app/(Layout)/components/HomePageCompo.tsx
  web/src/app/(Layout)/layout.tsx
  web/src/app/menu.tsx
Labels: 🎨 Html & Css, ⭐ Feature

#44 Home페이지, EditorCompo 수정
  web/package-lock.json
  web/package.json
  web/public/tinymce/icons/default/icons.min.js
  web/public/tinymce/langs/README.md
  web/public/tinymce/langs/ko_KR.js
  web/public/tinymce/license.txt
  web/public/tinymce/models/dom/model.min.js
  web/public/tinymce/plugins/image/plugin.min.js
  web/public/tinymce/plugins/link/plugin.min.js
  web/public/tinymce/plugins/lists/plugin.min.js
  web/public/tinymce/plugins/table/plugin.min.js
  web/public/tinymce/skins/content/default/content.js
  web/public/tinymce/skins/content/default/content.min.css
  web/public/tinymce/skins/ui/oxide/content.inline.js
  web/public/tinymce/skins/ui/oxide/content.inline.min.css
  web/public/tinymce/skins/ui/oxide/content.js
  web/public/tinymce/skins/ui/oxide/content.min.css
  web/public/tinymce/skins/ui/oxide/skin.js
  web/public/tinymce/skins/ui/oxide/skin.min.css
  web/public/tinymce/skins/ui/oxide/skin.shadowdom.js
  web/public/tinymce/skins/ui/oxide/skin.shadowdom.min.css
  web/public/tinymce/themes/silver/theme.min.js
  web/public/tinymce/tinymce.d.ts
  web/public/tinymce/tinymce.min.js
  web/src/app/(Layout)/components/EditorCompo.tsx
  web/src/app/(Layout)/components/HomePageCompo.tsx
  web/src/app/(Layout)/components/LoginCompo.tsx
  web/src/app/(Layout)/components/SelectPageCompo.tsx
  web/src/app/(Layout)/layout.tsx
  web/src/app/(NoLayout)/components/LoginForm.tsx
  web/src/app/common/formFile.ts
  web/src/app/lib/customFormFetch.ts
  web/src/app/menu.tsx
Labels: 🐛 BugFix, ⭐ Feature

#47 수정사항 반영
  web/src/app/(Layout)/admin/[category]/page.tsx
  web/src/app/(Layout)/admin/components/AdminComponent.tsx
  web/src/app/(Layout)/admin/components/ApplicationFormItem.tsx
  web/src/app/(Layout)/admin/components/BannerItem.tsx
  web/src/app/(Layout)/admin/components/BannerPostModal.tsx
  web/src/app/(Layout)/admin/components/CheckAdmin.tsx
  web/src/app/(Layout)/admin/components/CounselingItem.tsx
  web/src/app/(Layout)/admin/components/CounselingItemUpdateModal.tsx
  web/src/app/(Layout)/admin/components/DeleteModal.tsx
  web/src/app/(Layout)/admin/components/StaffComponent.tsx
  web/src/app/(Layout)/admin/components/StaffUpdateModal.tsx
  web/src/app/(Layout)/admin/layout.tsx
  web/src/app/(Layout)/admin/page.tsx
  web/src/app/(Layout)/components/HomePageCompo.tsx
  web/src/app/(Layout)/components/StaffIntro.tsx
  web/src/app/common/types.tsx
  web/src/app/menu.tsx
Labels: 🐛 BugFix, ⭐ Feature

#52 HomePageCompo, EditorCompo, HtmlDocs, BoardPageCompo수
  web/package-lock.json
  web/public/images/left.png
  web/public/images/right.png
  web/src/app/(Layout)/components/BoardPageCompo.tsx
  web/src/app/(Layout)/components/EditorCompo.tsx
  web/src/app/(Layout)/components/HomePageCompo.tsx
  web/src/app/(Layout)/components/HtmlDocs.tsx
  web/src/app/(Layout)/components/SelectPageCompo.tsx
Labels: ⭐ Feature

#57 24일 수정 사항
  web/public/images/close.png
  web/public/images/hamburger.png
  web/src/app/(Layout)/admin/components/AdminComponent.tsx
  web/src/app/(Layout)/admin/components/ApplicationFormItem.tsx
  web/src/app/(Layout)/admin/components/BannerItem.tsx
  web/src/app/(Layout)/admin/components/BannerPostModal.tsx
  web/src/app/(Layout)/admin/components/CheckAdmin.tsx
  web/src/app/(Layout)/admin/components/CounselingItem.tsx
  web/src/app/(Layout)/admin/components/CounselingItemUpdateModal.tsx
  web/src/app/(Layout)/admin/components/DeleteModal.tsx
  web/src/app/(Layout)/admin/components/StaffComponent.tsx
  web/src/app/(Layout)/admin/components/StaffModal.tsx
  web/src/app/(Layout)/board/[category]/page.tsx
  web/src/app/(Layout)/components/BoardDataMapCompo.tsx
  web/src/app/(Layout)/components/BoardPageCompo.tsx
  web/src/app/(Layout)/components/DashboardCompo.tsx
  web/src/app/(Layout)/components/EditorCompo.tsx
  web/src/app/(Layout)/components/FormCompo.tsx
  web/src/app/(Layout)/components/HamburgerMenuCompo.tsx
  web/src/app/(Layout)/components/HomePageCompo.tsx
  web/src/app/(Layout)/components/HtmlDocs.tsx
  web/src/app/(Layout)/components/LoginCompo.tsx
  web/src/app/(Layout)/components/MapCompo.tsx
  web/src/app/(Layout)/components/NameChangeModal.tsx
  web/src/app/(Layout)/components/NeedLinkCompo.tsx
  web/src/app/(Layout)/components/Pagination.tsx
  web/src/app/(Layout)/components/SelectPageCompo.tsx
  web/src/app/(Layout)/components/StaffIntro.tsx
  web/src/app/(Layout)/form/[category]/page.tsx
  web/src/app/(Layout)/guidance/[category]/page.tsx
  web/src/app/(Layout)/layout.tsx
  web/src/app/(Layout)/select/[category]/page.tsx
  web/src/app/(Layout)/staff-intro/page.tsx
  web/src/app/(Layout)/staff/[category]/page.tsx
  web/src/app/(NoLayout)/components/LoginForm.tsx
  web/src/app/(NoLayout)/components/RegisterCompo.tsx
  web/src/app/common/types.tsx
  web/src/app/menu.tsx
Labels: 🛠️ Refactor, ⭐ Feature

#61 메뉴 업데이트트
  web/src/app/(Layout)/admin/components/CheckAdmin.tsx
  web/src/app/(Layout)/components/HomePageCompo.tsx
  web/src/app/menu.tsx
Labels: ⭐ Feature

#65 ✨ feat : language변경, layout및 전 페이지 수정
  web/src/app/(Layout)/admin/components/AdminComponent.tsx
  web/src/app/(Layout)/admin/components/CheckAdmin.tsx
  web/src/app/(Layout)/board/[category]/[id]/page.tsx
  web/src/app/(Layout)/board/[category]/page.tsx
  web/src/app/(Layout)/components/BoardDataMapCompo.tsx
  web/src/app/(Layout)/components/BoardPageCompo.tsx
  web/src/app/(Layout)/components/DashboardCompo.tsx
  web/src/app/(Layout)/components/FormCompo.tsx
  web/src/app/(Layout)/components/HamburgerMenuCompo.tsx
  web/src/app/(Layout)/components/HomePageCompo.tsx
  web/src/app/(Layout)/components/HtmlDocs.tsx
  web/src/app/(Layout)/components/NameChangeModal.tsx
  web/src/app/(Layout)/components/NeedLinkCompo.tsx
  web/src/app/(Layout)/components/SelectPageCompo.tsx
  web/src/app/(Layout)/components/StaffIntro.tsx
  web/src/app/(Layout)/dashboard/page.tsx
  web/src/app/(Layout)/form/[category]/page.tsx
  web/src/app/(Layout)/guidance/[category]/page.tsx
  web/src/app/(Layout)/home/page.tsx
  web/src/app/(Layout)/layout.tsx
  web/src/app/(Layout)/select/[category]/page.tsx
  web/src/app/(Layout)/staff/[category]/page.tsx
  web/src/app/(NoLayout)/components/LoginForm.tsx
  web/src/app/(NoLayout)/components/RegisterCompo.tsx
  web/src/app/(NoLayout)/components/TermsAgreements.tsx
  web/src/app/hook/auth.ts
Labels: 🎨 Html & Css, 🛠️ Refactor
